baseURL = "https://yiyaotan-site.vercel.app/"
languageCode = "en-us"
title = "Yi Yao Tan"
theme = "ananke"

[params]
  description = "Graduate student specializing in Mathematics and Computer Science with extensive research experience."
  author = "Yi Yao Tan"
  mode = "light" # Choose 'light' or 'dark' mode for the theme
  mainSections = ["blog"]
  featured_image = "/images/default-featured.jpg"
  show_reading_time = true
  recent_posts_number = 3

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  # Use section + slug (e.g. /blog/life/dating/) just like the-prophet
  blog = "/:sections/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 4

[[menu.main]]
  name = "Resume"
  url = "/resume/"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
